import json

a2=open('outputs/datasetA2.json', 'r', encoding='utf8')
a3=open('outputs/datasetA3.json', 'r', encoding='utf8')
a4=open('outputs/datasetA4.json', 'r', encoding='utf8')
a6=open('outputs/datasetA6.json', 'r', encoding='utf8')
a7=open('outputs/datasetA7.json', 'r', encoding='utf8')
a8=open('outputs/datasetA8.json', 'r', encoding='utf8')
a9=open('outputs/datasetA9.json', 'r', encoding='utf8')
b1=open('outputs/datasetB1.json', 'r', encoding='utf8')
b4=open('outputs/datasetB4.json', 'r', encoding='utf8')
b6=open('outputs/datasetB6.json', 'r', encoding='utf8')
c1=open('outputs/datasetC1.json', 'r', encoding='utf8')

texta2 = a2.read()
texta3 = a3.read()
texta4 = a4.read()
texta6 = a6.read()
texta7 = a7.read()
texta8 = a8.read()
texta9 = a9.read()
textb1 = b1.read()
textb4 = b4.read()
textb6 = b6.read()
textc1 = c1.read()


obja2 = json.loads(texta2)
obja3 = json.loads(texta3)
obja4 = json.loads(texta4)
obja6 = json.loads(texta6)
obja7 = json.loads(texta7)
obja8 = json.loads(texta8)
obja9 = json.loads(texta9)
objb1 = json.loads(textb1)
objb4 = json.loads(textb4)
objb6 = json.loads(textb6)
objc1 = json.loads(textc1)

print(len(obja2))
print(len(obja3))
print(len(obja4))
print(len(obja6))
print(len(obja7))
print(len(obja8))
print(len(obja9))
print(len(objb1))
print(len(objb4))
print(len(objb6))
print(len(objc1))
